version: "3.8"

services:
  express:
    restart: always
    build: .
    ports:
      - "4000:4000"
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./public/:/app/public/
      - ./:/app
      - /app/node_modules
